version: '2.1'
services:
  boot:
    build: .
    image: boot:latest
    environment:
      PORT: 80
    expose:
      - "80"
    ports:
      - "3000:80"
    networks:
      blockchain:
        ipv4_address: 172.16.238.10
    labels:
        vutr.io: "Blockchain Network Boot Node"

  node:
    image: boot:latest
    depends_on:
      - boot
    expose:
      - "80"
    ports:
      - "3001-3010:80"
    command: ["/usr/src/app/delay.sh", "java", "-jar", "app-standalone.jar"]
    environment:
      BOOT_NODE: 172.16.238.10
      PORT: 80
    networks:
      - blockchain
    labels:
        vutr.io: "Blockchain Network Simulation Service"

networks:
  blockchain:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
